import{S as m,i}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();function u(r){const o=document.querySelector(".gallery");o.innerHTML="",r&&r.hits&&Array.isArray(r.hits)?r.hits.slice(0,9).forEach(t=>{const e=document.createElement("a");e.href=t.largeImageURL,e.rel="noopener noreferrer",e.classList.add("card"),e.innerHTML=`
                <img src="${t.webformatURL}" alt="${t.tags}">
                <div class="metrics">
                    ${a("Likes",t.likes).outerHTML}
                    ${a("Views",t.views).outerHTML}
                    ${a("Comments",t.comments).outerHTML}
                    ${a("Downloads",t.downloads).outerHTML}
                </div>
            `,o.appendChild(e)}):console.error("Invalid images data:",r)}function a(r,o){const n=document.createElement("div");n.classList.add("metric-container");const t=document.createElement("span");t.textContent=r,t.classList.add("metric-label"),t.style.fontWeight="bold",n.appendChild(t);const e=document.createElement("span");return e.textContent=o,e.classList.add("metric-value"),n.appendChild(e),n}function p(){const r=document.querySelector(".loading-indicator");r.textContent="Loading images, please wait...",r.style.display="block"}function l(){const r=document.querySelector(".loading-indicator");r.style.display="none"}function y(){const r=document.querySelector(".gallery");r.innerHTML=""}function d(){new m(".gallery a",{captionDelay:250}).refresh()}const h="42598538-444db408f0d8256d557c709b2",g="https://pixabay.com/api/";async function f(r){const o=`${g}?key=${h}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await fetch(o);if(!n.ok)throw new Error("HTTP Error: "+n.status);return await n.json()}catch(n){throw new Error("Error fetching images: "+n.message)}}async function L(r){r.preventDefault(),p(),y();const n=document.querySelector('.search-form input[type="text"]').value.trim();if(n===""){i.error({title:"Помилка",message:"Будь ласка, введіть текст для пошуку",position:"topCenter"}),l();return}try{const t=await f(n);t.hits.length===0?i.warning({title:"Увага",message:"Вибачте, результатів пошуку не знайдено. Спробуйте інший запит.",position:"topCenter"}):u(t)}catch(t){console.error(t.message),i.error({title:"Помилка",message:"Під час виконання запиту сталася помилка. Будь ласка, спробуйте ще раз.",position:"topCenter"})}finally{l()}}document.addEventListener("DOMContentLoaded",async function(){document.querySelector(".search-form").addEventListener("submit",async function(t){t.preventDefault(),await L(t),d()});const n=await f("your_default_query_here");u(n),d()});
//# sourceMappingURL=commonHelpers.js.map
